# CC		= gcc
# CFLAGS		= -Wall -Wextra
# CDEBUG		= -g
# LDFLAGS		= 
# LDLIBS		= 

# FILE		= hello
# OBJ           = hello.o

all:
	gcc equal.c -o equal

install:
	cp equal /usr/bin/equal; chmod a+x /usr/bin/equal

clean:
	rm -rf /usr/bin equal